---
config:
  theme: redux-color
---
%% REBASE GRAPH
gitGraph
   commit id: "Inital setup"
   commit id: "Create base-model"
   commit id: "Update README"
   branch update-params
   checkout update-params
   commit id: "Update parameters"
   commit id: "Evaluate the model"
