---
config:
  theme: redux-color
---
gitGraph
   commit id: "Initial setup"
   commit id: "Create base-model"
   commit id: "Update README"
   %% The commits from the branch are replayed on top of main
   commit id: "Update parameters"
   commit id: "Evaluate the model"
   %% The final integration point
   commit id: "Merge Commit" type: HIGHLIGHT
